### ISSUE TITLE
Visualization issue

### ISSUE THREAD

**Issue by DrChiZhang** [robden820/FluidSim#10]
Hi, I am trying to build your code, while the build is done, the simulation run with a issue in visualization as
a black screen without any particle or mesh data visualization. Any clue to this issue?

**Comment by DrChiZhang** [comment]
> Hi, I am trying to build your code, while the build is done, the simulation run with a issue in visualization as a black screen without any particle or mesh data visualization. Any clue to this issue?
Issue fixed. thx

**Comment by robden820** [comment]
Thanks for checking out this repository. Would you mind sharing more details about the error you had and the solution?

**Comment by DrChiZhang** [comment]
> Thanks for checking out this repository. Would you mind sharing more details about the error you had and the solution?

The path of shader files is not properly set.
